// Word-by-word timestamps for Surah Al-Mulk
// Generated by Whisper from audio recordings

export interface WordTimestamp {
  word: string;
  start: number;
  end: number;
}

export interface AyahTimestamps {
  ayah: number;
  words: WordTimestamp[];
}

// This will be populated by the build script
// For now, we'll load from JSON files dynamically
export const AYAH_TIMESTAMPS: Record<number, WordTimestamp[]> = {};

// Fallback: evenly distribute words if no timestamps available
export function getWordTimestamps(ayah: number, wordCount: number, duration: number): WordTimestamp[] {
  if (AYAH_TIMESTAMPS[ayah]) {
    return AYAH_TIMESTAMPS[ayah];
  }
  
  // Fallback: even distribution
  const wordDuration = duration / wordCount;
  return Array.from({ length: wordCount }, (_, i) => ({
    word: '',
    start: i * wordDuration,
    end: (i + 1) * wordDuration
  }));
}
